import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-800 text-white p-4 mb-10">
          <div className="container mx-auto">
            <h1 className="text-2xl font-bold">Example</h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
